### ISSUE TITLE
希望可以增加外接数据库

### ISSUE THREAD

**Issue by AkimioJR** [sxbai/halo-on-replit#1]
希望可以增加外接数据库，避免博客被replit禁用而无法取回数据
外接数据库
bit.io
db4free.net

**Comment by sxbai** [comment]
首先博客被replit禁用也是可以取回数据的，方法：换个账号fork你被封禁博客的项目，就可以在新的账户项目里得到被封禁的项目里面的数据。增加数据库可以考虑一下。

**Comment by AkimioJR** [comment]
halo在docker-compose的启动模式下是支持第三方数据库的，我仿照命令在main.sh中增加相关参数好像会导致repls无法启动

**Comment by sxbai** [comment]
要不学习一下怎么编译halo的jar文件？从源代码入手更改数据库信息更容易些，我是使用github codespace编译的。

**Comment by AkimioJR** [comment]
请问哪里可以找到参考教程，我已jar github codepace为关键词找不到，不知道这个没有编程基础的可不可以学习

**Comment by JohnNiang** [comment]
> 从源代码入手更改数据库信息更容易些

目前可以通过`环境变量`、`命令行参数`和`外部配置文件（application.yaml）`修改系统的配置，直接从源码修改病打包可能不是一个合适的选择。

**Comment by AkimioJR** [comment]
> > 从源代码入手更改数据库信息更容易些
> 
> 
> 
> 目前可以通过`环境变量`、`命令行参数`和`外部配置文件（application.yaml）`修改系统的配置，直接从源码修改病打包可能不是一个合适的选择。

小白，不太会这些操作

**Comment by sxbai** [comment]
> > > 从源代码入手更改数据库信息更容易些
> > 
> > 
> > 目前可以通过、和修改系统的配置，直接从源码修改病打包可能不是一个合适的选择。`环境变量``命令行参数``外部配置文件（application.yaml）`
> 
> 小白，不太会这些操作

<img width="464" alt="image" src="https://user-images.githubusercontent.com/55978160/227473258-83ae7e51-f37a-4434-a099-b5d15e3f0d01.png">
<img width="469" alt="image" src="https://user-images.githubusercontent.com/55978160/227473200-7522e8e0-a8ee-4134-8633-909f454dcbb2.png">

**Comment by AkimioJR** [comment]
> > > > 从源代码入手更改数据库信息更容易些
> > > 
> > > 
> > > 目前可以通过、和修改系统的配置，直接从源码修改病打包可能不是一个合适的选择。`` 环境变量``命令行参数``外部配置文件（application.yaml） ``
> > 
> > 
> > 小白，不太会这些操作
> 
> <img alt="image" width="464" src="https://user-images.githubusercontent.com/55978160/227473258-83ae7e51-f37a-4434-a099-b5d15e3f0d01.png">
> 
> <img alt="image" width="469" src="https://user-images.githubusercontent.com/55978160/227473200-7522e8e0-a8ee-4134-8633-909f454dcbb2.png">

我看到这个了，应该是在docker-compose下面的吧，但我不会修改源码
