### ISSUE TITLE
出个教程吧

### ISSUE THREAD

**Issue by aizhiqian** [sxbai/halo-on-replit#2]
怎么重新编译打包啊，可以出个教程吗，小白一个

**Comment by sxbai** [comment]
利用Github codespace进行编译，编译文档参考halo官方文档

--------------原始邮件--------------
发件人："YJC ***@***.***&gt;;
发送时间：2023年4月5日(星期三) 下午2:23
收件人："sxbai/halo-on-replit" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[sxbai/halo-on-replit] 出个教程吧 (Issue #2)
-----------------------------------

 

 
怎么重新编译打包啊，可以出个教程吗，小白一个

**Comment by aizhiqian** [comment]
如何修改工作目录啊
